FROM ubuntu:jammy

ENV PETSC_DIR=/scratch/petsc PETSC_ARCH=petsc-arch
ARG PETSC_VERSION

RUN apt update -qq && \
    apt install -y git make cmake gcc gfortran g++ lcov gawk
RUN apt install -y python3 python3-h5py
RUN apt install -y wget
RUN apt install -y vim

# intel compilers (icc, icx, icpc, icpx, ifort, ifx)
RUN wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/89283df8-c667-47b0-b7e1-c4573e37bd3e/l_dpcpp-cpp-compiler_p_2023.1.0.46347.sh
RUN sh ./l_dpcpp-cpp-compiler_p_2023.1.0.46347.sh -a --silent --eula accept
RUN wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/150e0430-63df-48a0-8469-ecebff0a1858/l_fortran-compiler_p_2023.1.0.46348.sh
RUN sh ./l_fortran-compiler_p_2023.1.0.46348.sh -a --silent --eula accept

WORKDIR /scratch
RUN wget https://www.mpich.org/static/downloads/4.1/mpich-4.1.tar.gz
COPY ./.gitlab/build-petsc-intel.sh .
RUN /scratch/build-petsc-intel.sh
