FROM ubuntu:jammy

ENV PETSC_DIR=/scratch/petsc PETSC_ARCH=petsc-arch
ARG PETSC_VERSION

RUN apt update -qq && \
    apt install -y git make cmake lcov
RUN apt install -y python3 python3-h5py
RUN apt install -y wget
RUN apt install -y vim

# intel compilers
RUN wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/7deeaac4-f605-4bcf-a81b-ea7531577c61/l_BaseKit_p_2023.1.0.46401.sh
RUN sh ./l_BaseKit_p_2023.1.0.46401.sh -a --silent --eula accept --components intel.oneapi.lin.dpcpp-cpp-compiler
RUN sh ./l_BaseKit_p_2023.1.0.46401.sh -a --silent --eula accept --components intel.oneapi.lin.dpl
RUN wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/1ff1b38a-8218-4c53-9956-f0b264de35a4/l_HPCKit_p_2023.1.0.46346.sh
RUN sh ./l_HPCKit_p_2023.1.0.46346.sh -a --silent --eula accept --components intel.oneapi.lin.ifort-compiler
RUN sh ./l_HPCKit_p_2023.1.0.46346.sh -a --silent --eula accept --components intel.oneapi.lin.mpi.devel
RUN sh ./l_HPCKit_p_2023.1.0.46346.sh -a --silent --eula accept --components intel.oneapi.lin.dpcpp-cpp-compiler-pro

RUN source /opt/intel/oneapi/setvars.sh
RUN export PATH = /opt/intel/oneapi/mpi/2021.9.0/bin:/opt/intel/oneapi/compiler/2023.1.0/linux/bin/intel64:/opt/intel/oneapi/compiler/2023.1.0/linux/bin:$PATH
RUN ifort --version \
    icc --version \
    icpc --version

WORKDIR /scratch
RUN wget https://www.mpich.org/static/downloads/4.1/mpich-4.1.tar.gz


COPY ./.gitlab/build-petsc-intel.sh .
RUN /scratch/build-petsc-intel.sh

