ARG IMAGE
FROM $IMAGE
ENV PETSC_DIR=/scratch/petsc-intel PETSC_ARCH=petsc-arch-intel

WORKDIR /scratch
COPY . .
RUN ./.gitlab/info.sh
RUN ./.gitlab/build-pflotran-intel.sh

# Make sure pflotran is properly built
RUN pflotran -help intro
