FROM ubuntu:jammy

ENV PETSC_DIR=/scratch/petsc PETSC_ARCH=petsc-arch
ARG PETSC_VERSION

RUN apt update -qq && \
    apt install -y git make cmake lcov
RUN apt install -y python3 python3-h5py
RUN apt install -y wget
RUN apt install -y vim

# intel compilers
RUN apt install -y gpg-agent
RUN wget -qO - https://repositories.intel.com/graphics/intel-graphics.key | apt-key add -
RUN apt-add-repository 'deb [arch=amd64] https://repositories.intel.com/graphics/ubuntu focal main'
RUN apt update -qq
RUN apt install intel-opencl-icd intel-level-zero-gpu level-zero intel-media-va-driver-non-free libmfx1
RUN wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
RUN apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
RUN rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
RUN echo "deb https://apt.repos.intel.com/oneapi all main" | tee /etc/apt/sources.list.d/oneAPI.list
RUN apt update -qq
RUN apt install -y \
    intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic-common-2023.1.0 \
    intel-oneapi-compiler-fortran-2023.1.0 \
    intel-oneapi-mpi-devel-2021.9.0

RUN source /opt/intel/oneapi/setvars.sh
RUN ifort --version \
    icc --version \
    icpc --version

WORKDIR /scratch
RUN wget https://www.mpich.org/static/downloads/4.1/mpich-4.1.tar.gz


COPY ./.gitlab/build-petsc-intel.sh .
RUN /scratch/build-petsc-intel.sh

